version: '3'
services:
  client:
    build:
      context: './react_dock'
      dockerfile: Dockerfile
    ports:
      - 3000:80
    container_name: react_dock_cont
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-docker-network
    volumes:
      - ./react_dock:/app
    depends_on:
      - backend
  backend:
    build:
      context: './node_dock'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: node_dock_cont
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-docker-network
    volumes:
      - ./node_dock:/app
networks:
  mern-docker-network: